---
- name: Install Apache Web Server
  apt:
    name: apache2
    state: present
    update_cache: yes
  become: true

- name: Create node-specific index.html file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0444'
  notify: Restart Apache
  become: true

- name: Ensure Apache is started
  service:
    name: apache2
    state: started
    enabled: true
  become: true
